### ISSUE TITLE
ml.plots.stresses() does not work for StressModel2

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#158]
The error is as follows:

Traceback (most recent call last):

  File "<ipython-input-42-3ad88a276ec1>", line 1, in <module>
    ml.plots.stresses()

  File "c:\users\artesia\documents\github\pastas\pastas\decorators.py", line 40, in _model_tmin_tmax
    return function(self, tmin, tmax, *args, **kwargs)

  File "c:\users\artesia\documents\github\pastas\pastas\plots.py", line 460, in stresses
    stress = self.ml.get_stress(name, istress=istress)

  File "c:\users\artesia\documents\github\pastas\pastas\decorators.py", line 27, in _get_stressmodel
    return function(self, name, **kwargs)

  File "c:\users\artesia\documents\github\pastas\pastas\model.py", line 1339, in get_stress
    stress = self.stressmodels[name].get_stress(p=parameters, **kwargs)

TypeError: get_stress() got an unexpected keyword argument 'tmin'

**Comment by rubencalje** [comment]
Fixed by commit d7837d3dbb303a7498c7a8e69c070e27a47ffb6e
